[package]
name = "gui_core_00"
version = "0.1.0"
authors = ["Ben Pinhorn <00ben.allen@gmail.com>"]
edition = "2018"

[dependencies]
gfx = "0.17"
glutin = "0.19.0"
gfx_window_glutin = "0.28.0"
image = "0.21.0"
gfx_device_gl = "0.15.5"
gfx_core = "0.8.3"
